"""SP bit-for-bit acceptance gate for the muP retrofit.

Replays the committed golden fixtures (generated by scripts/gen_sp_baseline.py
from the pre-muP tree) and requires BITWISE identical per-tensor state hashes
at init and after 5 seeded optimizer steps. Failure localizes to the exact
tensor that diverged.

Layer 2 (added with the retrofit): a same-process A/B check that a config
with no mup key and a config with mup.enabled=False produce bitwise-equal
trajectories.

Torch version mismatch HARD-FAILS (never skips): regenerate fixtures from the
pre-muP commit under the new torch before trusting the gate again.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest
import torch

from trackfm.config import ModelConfig, NormalizationConfig
from trackfm.models.encoder import CausalAISModel
from trackfm.training.losses import (compute_soft_target_loss,
                                       cone_elapsed_seconds, cone_ranges)
from trackfm.training.pretrain import _lr_lambda

REF = Path(__file__).resolve().parents[1] / "reference"
FIXTURES = sorted(REF.glob("sp_baseline_*.json"))
SEQ, MAX_H, N_H = 32, 64, 4


def _state_hashes(model):
    per_tensor = {}
    whole = hashlib.sha256()
    for k, v in sorted(model.state_dict().items()):
        b = v.detach().cpu().contiguous().numpy().tobytes()
        per_tensor[k] = hashlib.sha256(b).hexdigest()
        whole.update(k.encode())
        whole.update(b)
    return per_tensor, whole.hexdigest()


def _synth_batch(norm):
    g = torch.Generator().manual_seed(123)
    B, T = 8, SEQ + MAX_H
    lat0 = 56.0 + 0.5 * torch.rand(B, 1, generator=g)
    lon0 = 11.0 + 0.5 * torch.rand(B, 1, generator=g)
    step_deg = 0.001 * torch.randn(B, 2, generator=g)
    t_idx = torch.arange(T).float()[None, :]
    lat = lat0 + step_deg[:, 0:1] * t_idx
    lon = lon0 + step_deg[:, 1:2] * t_idx
    sog = 5.0 + 3.0 * torch.rand(B, 1, generator=g).expand(B, T)
    cog = (360.0 * torch.rand(B, 1, generator=g)).expand(B, T)
    dt = 60.0 + 30.0 * torch.rand(B, T, generator=g)
    return torch.stack([
        (lat - norm.lat_center) / norm.lat_scale,
        (lon - norm.lon_center) / norm.lon_scale,
        sog / norm.sog_scale,
        torch.sin(torch.deg2rad(cog)),
        torch.cos(torch.deg2rad(cog)),
        dt / norm.dt_scale,
    ], dim=-1).float()


def _replay(over: dict, fx: dict):
    torch.use_deterministic_algorithms(True)
    torch.set_num_threads(1)
    norm = NormalizationConfig()
    m = ModelConfig(d_model=32, nhead=4, num_layers=2, dim_feedforward=64,
                    dropout=0.1, max_seq_len=SEQ, grid_size=16,
                    grid_range=0.3, num_freqs=3, **over)
    torch.manual_seed(0)
    model = CausalAISModel(m, norm, max_horizon=MAX_H, num_horizon_samples=N_H)
    model.train()
    init_pt, init_whole = _state_hashes(model)

    opt = torch.optim.AdamW(model.parameters(), lr=fx["lr"],
                            weight_decay=fx["wd"])
    sched = torch.optim.lr_scheduler.LambdaLR(
        opt, lambda s: _lr_lambda(s, fx["warmup"], fx["max_steps"], "cosine"))
    batch = _synth_batch(norm)
    losses = []
    for _ in range(fx["steps"]):
        ld, tgt, hz, _ = model.forward_train(batch, causal=True)
        if m.grid_mode == "cone":
            el = cone_elapsed_seconds(batch, hz, m.max_seq_len,
                                      norm.dt_scale, causal=True)
            tgt = tgt / cone_ranges(el, m.cone_r0, m.cone_v, m.cone_p)
            loss = compute_soft_target_loss(ld.float(), tgt.float(), 1.0,
                                            m.grid_size, 0.003 / m.grid_range)
        else:
            loss = compute_soft_target_loss(ld.float(), tgt.float(),
                                            m.grid_range, m.grid_size, 0.003)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        opt.step()
        opt.zero_grad(set_to_none=True)
        sched.step()
        losses.append(repr(loss.item()))
    final_pt, final_whole = _state_hashes(model)
    return init_pt, init_whole, final_pt, final_whole, losses


@pytest.mark.parametrize("path", FIXTURES, ids=lambda p: p.stem)
def test_sp_bitwise_baseline(path):
    fx = json.loads(path.read_text())
    assert fx["torch_version"] == torch.__version__, (
        f"torch changed ({fx['torch_version']} -> {torch.__version__}): "
        "regenerate fixtures from the pre-muP commit; NEVER skip this gate.")

    init_pt, init_whole, final_pt, final_whole, losses = _replay(
        fx["config_overrides"], fx)

    for k, h in fx["step0"]["per_tensor"].items():
        assert init_pt.get(k) == h, f"INIT diverged at tensor {k}"
    assert init_whole == fx["step0"]["whole"], "init whole-state hash diverged"

    for k, h in fx["step5"]["per_tensor"].items():
        assert final_pt.get(k) == h, f"STEP-5 state diverged at tensor {k}"
    assert final_whole == fx["step5"]["whole"], "step-5 whole-state hash diverged"
    assert losses == fx["losses"], "loss trajectory diverged"


def test_fixture_coverage():
    """All five variants present — the gate has no blind head/geometry cell."""
    names = {p.stem.replace("sp_baseline_", "") for p in FIXTURES}
    assert names == {"fourier_fixed", "fourier_cone", "direct_fixed",
                     "direct_cone", "fourier_fixed_mlp32"}, names
